# Generated by Django 3.2.18 on 2023-04-16 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0002_auto_20230416_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modification',
            name='description',
        ),
        migrations.RemoveField(
            model_name='modification',
            name='name',
        ),
    ]
