# Generated by Django 3.2.18 on 2023-04-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0006_auto_20230418_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphicscard',
            name='number_of_universal_processors',
        ),
        migrations.RemoveField(
            model_name='graphicscard',
            name='video_memory_bus_bit_rate',
        ),
        migrations.RemoveField(
            model_name='graphicscard',
            name='video_memory_frequency',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='number_of_3_5_internal_bays',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='number_of_5_25_bays',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='power_supply_unit_location',
        ),
        migrations.RemoveField(
            model_name='powersupplyunit',
            name='adjustable_fan_speed',
        ),
        migrations.RemoveField(
            model_name='powersupplyunit',
            name='molex_connectors',
        ),
        migrations.RemoveField(
            model_name='powersupplyunit',
            name='pci_e_connectors',
        ),
        migrations.RemoveField(
            model_name='powersupplyunit',
            name='power_connectors',
        ),
        migrations.RemoveField(
            model_name='powersupplyunit',
            name='sata_connectors',
        ),
        migrations.RemoveField(
            model_name='powersupplyunit',
            name='standard',
        ),
        migrations.AddField(
            model_name='accessory',
            name='performance',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cooling',
            name='performance',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='graphicscard',
            name='length',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graphicscard',
            name='performance',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='housing',
            name='height',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='housing',
            name='length',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='housing',
            name='performance',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='housing',
            name='width',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memory',
            name='performance',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modification',
            name='author_id',
            field=models.PositiveIntegerField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modification',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='performance',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='powersupplyunit',
            name='efficiency',
            field=models.CharField(choices=[('80 PLUS', '80 PLUS'), ('80 PLUS Bronze', '80 PLUS Bronze'), ('80 PLUS Silver', '80 PLUS Silver'), ('80 PLUS Gold', '80 PLUS Gold'), ('80 PLUS Platinum', '80 PLUS Platinum')], default=None, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='powersupplyunit',
            name='form_factor',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='powersupplyunit',
            name='noise_level',
            field=models.CharField(choices=[('A++', '<15 dB(A)'), ('A+', '≥15 dB(A) & <20 dB(A)'), ('A', '≥20 dB(A) & <25 dB(A)'), ('A-', '≥25 dB(A) & <30 dB(A)'), ('STANDARD ++', '≥30 dB(A) & <35 dB(A)'), ('STANDARD +', '≥35 dB(A) & <40 dB(A)'), ('STANDARD', '≥40 dB(A) & <45 dB(A)')], default='A++', max_length=20),
        ),
        migrations.AddField(
            model_name='powersupplyunit',
            name='performance',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processor',
            name='performance',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ram',
            name='performance',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='graphicscard',
            name='video_memory_type',
            field=models.CharField(choices=[('DDR', 'DDR'), ('DDR2', 'DDR2'), ('DDR3', 'DDR3'), ('DDR4', 'bDDR4')], max_length=6),
        ),
        migrations.AlterField(
            model_name='memory',
            name='memory_type',
            field=models.CharField(choices=[('HDD', 'HDD'), ('SSD', 'SSD')], default='SSD', max_length=3),
        ),
        migrations.AlterField(
            model_name='ram',
            name='memory_type',
            field=models.CharField(choices=[('DDR', 'DDR'), ('DDR2', 'DDR2'), ('DDR3', 'DDR3'), ('DDR4', 'bDDR4')], max_length=4),
        ),
    ]
