# Generated by Django 3.2.18 on 2023-04-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0007_auto_20230425_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='disk_capacity',
            field=models.IntegerField(help_text='in GB'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='form_factor',
            field=models.CharField(choices=[('E-ATX', 'E-ATX for FullTower (305mm x 330mm)'), ('ATX', 'ATX for MidiTower (244mm x 305mm)'), ('Micro-ATX', 'Micro-ATX for MiniTower (244mm x 244mm)')], max_length=40),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='num_memory_slots',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='socket',
            field=models.CharField(choices=[('LGA1151', 'LGA1151'), ('LGA1200', 'LGA1200'), ('LGA1700', 'LGA1700'), ('LGA2066', 'LGA2066'), ('AM4', 'AM4'), ('TR4', 'TR4'), ('sTRX4', 'sTRX4')], max_length=50),
        ),
        migrations.AlterField(
            model_name='powersupplyunit',
            name='form_factor',
            field=models.CharField(choices=[('ATX', 'ATX'), ('SFX', 'SFX'), ('TFX', 'TFX'), ('Flex-ATX', 'Flex-ATX')], max_length=50),
        ),
        migrations.AlterField(
            model_name='processor',
            name='clock_frequency',
            field=models.FloatField(help_text='in MHz'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='socket',
            field=models.CharField(choices=[('LGA1151', 'LGA1151'), ('LGA1200', 'LGA1200'), ('LGA1700', 'LGA1700'), ('LGA2066', 'LGA2066'), ('AM4', 'AM4'), ('TR4', 'TR4'), ('sTRX4', 'sTRX4')], max_length=10),
        ),
    ]
