# Generated by Django 3.2.18 on 2023-04-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0009_alter_graphicscard_video_memory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphicscard',
            name='length',
            field=models.PositiveIntegerField(help_text='in mm'),
        ),
    ]
