# Generated by Django 3.2.18 on 2023-04-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0011_alter_graphicscard_video_memory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphicscard',
            name='video_memory_type',
            field=models.CharField(choices=[('DDR', 'DDR'), ('DDR2', 'DDR2'), ('DDR3', 'DDR3'), ('DDR4', 'DDR4'), ('DDR5', 'DDR5')], max_length=6),
        ),
    ]
