# Generated by Django 3.2.18 on 2023-04-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0015_auto_20230425_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modification',
            name='author_id',
        ),
        migrations.AddField(
            model_name='modification',
            name='author_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
