# Generated by Django 3.2.18 on 2023-04-26 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0018_auto_20230426_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socket', models.CharField(choices=[('LGA1150', 'LGA1150'), ('LGA1151', 'LGA1151'), ('LGA1155', 'LGA1155'), ('LGA1156', 'LGA1156'), ('LGA1200', 'LGA1200'), ('LGA1700', 'LGA1700'), ('LGA2011', 'LGA2011'), ('LGA2011 v3', 'LGA2011 v3'), ('LGA2066', 'LGA2066'), ('AM4', 'AM4'), ('sTR4', 'sTR4')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='cooling',
            name='socket',
        ),
        migrations.AddField(
            model_name='cooling',
            name='socket',
            field=models.ManyToManyField(to='configurator.Socket'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='socket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurator.socket'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='socket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurator.socket'),
        ),
    ]
