# Generated by Django 3.2.18 on 2023-04-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0019_auto_20230426_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socket',
            name='socket',
            field=models.CharField(choices=[('LGA1150', 'LGA1150'), ('LGA1151', 'LGA1151'), ('LGA1155', 'LGA1155'), ('LGA1156', 'LGA1156'), ('LGA1200', 'LGA1200'), ('LGA1700', 'LGA1700'), ('LGA2011', 'LGA2011'), ('LGA2011 v3', 'LGA2011 v3'), ('LGA2066', 'LGA2066'), ('AM4', 'AM4'), ('sTR4', 'sTR4')], max_length=20, unique=True),
        ),
    ]
