# Generated by Django 3.2.18 on 2023-04-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0020_alter_socket_socket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modification',
            old_name='processor',
            new_name='cpu',
        ),
        migrations.RenameField(
            model_name='modification',
            old_name='graphics_card',
            new_name='gpu',
        ),
        migrations.AlterField(
            model_name='cooling',
            name='socket',
            field=models.ManyToManyField(related_name='sockets', to='configurator.Socket'),
        ),
    ]
