# Generated by Django 3.2.18 on 2023-04-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0021_auto_20230426_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modification',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
