# Generated by Django 4.1.7 on 2023-04-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0022_alter_modification_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessory',
            old_name='performance',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='cooling',
            old_name='performance',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='cooling',
            old_name='socket',
            new_name='sockets',
        ),
        migrations.RenameField(
            model_name='cpu',
            old_name='performance',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='gpu',
            old_name='performance',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='housing',
            old_name='performance',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='memory',
            old_name='performance',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='performance',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='powersupplyunit',
            old_name='performance',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='ram',
            old_name='performance',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='static',
        ),
        migrations.RemoveField(
            model_name='cooling',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='cooling',
            name='static',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='static',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='static',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='static',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='static',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='static',
        ),
        migrations.RemoveField(
            model_name='powersupplyunit',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='powersupplyunit',
            name='static',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='static',
        ),
        migrations.AddField(
            model_name='accessory',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='type',
            field=models.CharField(blank=True, choices=[('Cooling', 'Cooling'), ('Memory', 'Memory'), ('Housing', 'Housing'), ('CPU', 'CPU'), ('Motherboard', 'Motherboard'), ('GPU', 'GPU'), ('RAM', 'RAM'), ('PowerSupplyUnit', 'PowerSupplyUnit')], max_length=50),
        ),
        migrations.AddField(
            model_name='cooling',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
        migrations.AddField(
            model_name='cooling',
            name='type',
            field=models.CharField(blank=True, choices=[('Cooling', 'Cooling'), ('Memory', 'Memory'), ('Housing', 'Housing'), ('CPU', 'CPU'), ('Motherboard', 'Motherboard'), ('GPU', 'GPU'), ('RAM', 'RAM'), ('PowerSupplyUnit', 'PowerSupplyUnit')], max_length=50),
        ),
        migrations.AddField(
            model_name='cpu',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='type',
            field=models.CharField(blank=True, choices=[('Cooling', 'Cooling'), ('Memory', 'Memory'), ('Housing', 'Housing'), ('CPU', 'CPU'), ('Motherboard', 'Motherboard'), ('GPU', 'GPU'), ('RAM', 'RAM'), ('PowerSupplyUnit', 'PowerSupplyUnit')], max_length=50),
        ),
        migrations.AddField(
            model_name='gpu',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='type',
            field=models.CharField(blank=True, choices=[('Cooling', 'Cooling'), ('Memory', 'Memory'), ('Housing', 'Housing'), ('CPU', 'CPU'), ('Motherboard', 'Motherboard'), ('GPU', 'GPU'), ('RAM', 'RAM'), ('PowerSupplyUnit', 'PowerSupplyUnit')], max_length=50),
        ),
        migrations.AddField(
            model_name='housing',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
        migrations.AddField(
            model_name='housing',
            name='type',
            field=models.CharField(blank=True, choices=[('Cooling', 'Cooling'), ('Memory', 'Memory'), ('Housing', 'Housing'), ('CPU', 'CPU'), ('Motherboard', 'Motherboard'), ('GPU', 'GPU'), ('RAM', 'RAM'), ('PowerSupplyUnit', 'PowerSupplyUnit')], max_length=50),
        ),
        migrations.AddField(
            model_name='memory',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
        migrations.AddField(
            model_name='memory',
            name='type',
            field=models.CharField(blank=True, choices=[('Cooling', 'Cooling'), ('Memory', 'Memory'), ('Housing', 'Housing'), ('CPU', 'CPU'), ('Motherboard', 'Motherboard'), ('GPU', 'GPU'), ('RAM', 'RAM'), ('PowerSupplyUnit', 'PowerSupplyUnit')], max_length=50),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='type',
            field=models.CharField(blank=True, choices=[('Cooling', 'Cooling'), ('Memory', 'Memory'), ('Housing', 'Housing'), ('CPU', 'CPU'), ('Motherboard', 'Motherboard'), ('GPU', 'GPU'), ('RAM', 'RAM'), ('PowerSupplyUnit', 'PowerSupplyUnit')], max_length=50),
        ),
        migrations.AddField(
            model_name='powersupplyunit',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
        migrations.AddField(
            model_name='powersupplyunit',
            name='type',
            field=models.CharField(blank=True, choices=[('Cooling', 'Cooling'), ('Memory', 'Memory'), ('Housing', 'Housing'), ('CPU', 'CPU'), ('Motherboard', 'Motherboard'), ('GPU', 'GPU'), ('RAM', 'RAM'), ('PowerSupplyUnit', 'PowerSupplyUnit')], max_length=50),
        ),
        migrations.AddField(
            model_name='ram',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
        migrations.AddField(
            model_name='ram',
            name='type',
            field=models.CharField(blank=True, choices=[('Cooling', 'Cooling'), ('Memory', 'Memory'), ('Housing', 'Housing'), ('CPU', 'CPU'), ('Motherboard', 'Motherboard'), ('GPU', 'GPU'), ('RAM', 'RAM'), ('PowerSupplyUnit', 'PowerSupplyUnit')], max_length=50),
        ),
        migrations.AlterField(
            model_name='memory',
            name='read_speed',
            field=models.FloatField(help_text='in mb/s'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='write_speed',
            field=models.FloatField(help_text='in mb/s'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='memory_capacity',
            field=models.PositiveIntegerField(help_text='in GB'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='memory_clock_speed',
            field=models.PositiveIntegerField(help_text='in Mhz'),
        ),
    ]
