# Generated by Django 4.1.7 on 2023-04-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0022_alter_modification_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='static',
        ),
        migrations.RemoveField(
            model_name='cooling',
            name='static',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='static',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='static',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='static',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='static',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='static',
        ),
        migrations.RemoveField(
            model_name='powersupplyunit',
            name='static',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='static',
        ),
        migrations.AddField(
            model_name='accessory',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
        migrations.AddField(
            model_name='cooling',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
        migrations.AddField(
            model_name='housing',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
        migrations.AddField(
            model_name='memory',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
        migrations.AddField(
            model_name='powersupplyunit',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
        migrations.AddField(
            model_name='ram',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
    ]
